name: CI Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12  

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  

      - name: Run notebook
        run: |
          pip install nbconvert  
          jupyter nbconvert --to notebook --execute week-9-mini-project_zihan-xiao.ipynb  

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: notebook-results
          path: week-9-mini-project_zihan-xiao.ipynb  